//
//  ProductListViewController.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 22/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductListViewController: UIViewController {

    var interactor: ProductListBusinessLogic?
    var router: (NSObjectProtocol & ProductListRoutingLogic & ProductListDataPassing)?

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    private func setup() {
        let viewController = self
        let interactor = ProductListInteractor()
        let presenter = ProductListPresenter()
        let router = ProductListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableview()
        setupView()
    }
    
    @IBOutlet weak var productsTableView: UITableView!
    
    private func setupTableview() {
        productsTableView.tableFooterView = UIView()
        productsTableView.register(
            UINib(nibName: R.nib.productTableViewCell.name, bundle: nil),
            forCellReuseIdentifier: R.string.cells.product_cell()
        )
    }
    
    private func setupView() {
        interactor?.setupTitleWithCategoryName()
        interactor?.setupLoadingState()
        interactor?.requestProductsByCategory()
    }
    
}
