//
//  ProductListWorker.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 22/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class ProductListWorker {
    
    let networkProvider = NetworkProvider.shared
    
    func getProductsByCategory(id categoryId: Int, offset: Int, limit: Int) -> Promise<ProductList.Response> {
        return networkProvider.request(.getProducts(offset: offset, limit: limit, categoryId: categoryId))
    }

}
