//
//  ProductListModels.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 22/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum ProductList {
  
    class Response: BaseResponse<[ProductModel]> {
        override init(data: [ProductModel]) {
            super.init(data: data)
        }
        
        required init(from decoder: Decoder) throws {
            try super.init(from: decoder)
        }
    }
    
    struct ViewModel {
        let bestSellers: [ProductViewModel]
    }

}
