//
//  ProductListPresenter.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 22/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListPresentationLogic {
    func presentTitleWithCategory(name categoryName: String)
    func presentLoadingState()
    func presentEmptyState()
    func presentDynamicData()
    func presentRequestError(_ error: Error)
}

class ProductListPresenter: ProductListPresentationLogic {

    weak var viewController: ProductListDisplayLogic?

    func presentTitleWithCategory(name categoryName: String) {
        viewController?.displayTitleWithCategory(name: categoryName)
    }
    
    func presentLoadingState() {
        viewController?.displayLoadingState()
    }
    
    func presentEmptyState() {
        viewController?.displayEmptyState()
    }
    
    func presentDynamicData() {
        viewController?.displayDynamicData()
    }
    
    func presentRequestError(_ error: Error) {
        viewController?.displayRequestError(message: error.localizedDescription)
    }
    
}
