# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test.AmeDigitalLodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test.AmeDigitalLodjinha
  pod "PromiseKit", "~> 6.8"
  pod "SDWebImage", "~> 5.0"
  pod "R.swift"

  target 'Test.AmeDigitalLodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test.AmeDigitalLodjinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
