//
//  ProductDetailsModels.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 20/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetails {
    
    struct ViewModel {
        
        let id: Int
        let name: String
        let description: String
        let category: String
        let imageUrl: String
        let oldPrice: Double
        let currentPrice: Double
        
        init(product: ProductModel) {
            self.id = product.id
            self.name = product.name
            self.description = product.description
            self.category = product.category.description
            self.imageUrl = product.imageUrl
            self.oldPrice = product.oldPrice
            self.currentPrice = product.currentPrice
        }
        
    }
    
    enum Reserve {
        struct Response: Codable {
            let result: String
        }
    }

}
