//
//  ProductDetailsPresenter.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 20/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsPresentationLogic {
    func presentProductDetails(product: ProductModel)
}

class ProductDetailsPresenter: ProductDetailsPresentationLogic {

    weak var viewController: ProductDetailsDisplayLogic?
    
    func presentProductDetails(product: ProductModel) {
        viewController?.displayProductDetails(viewModel: ProductDetails.ViewModel(product: product))
        viewController?.displayReserveProductButton()
    }
    
}
