//
//  ProductDetailsInteractor.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 20/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsBusinessLogic {
    func doSomething(request: ProductDetails.Something.Request)
}

protocol ProductDetailsDataStore {
    //var name: String { get set }
}

class ProductDetailsInteractor: ProductDetailsBusinessLogic, ProductDetailsDataStore {

    var presenter: ProductDetailsPresentationLogic?
    var worker: ProductDetailsWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: ProductDetails.Something.Request) {
        worker = ProductDetailsWorker()
        worker?.doSomeWork()
        
        let response = ProductDetails.Something.Response()
        presenter?.presentSomething(response: response)
    }

}
