//
//  ProductDetailsWorker.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 20/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import PromiseKit

class ProductDetailsWorker {

    let networkProvider = NetworkProvider.shared
    
    func requestReserveForProduct(id productId: Int) -> Promise<ProductDetails.Reserve.Response> {
        return networkProvider.request(.reserveProductBy(id: productId))
    }

}
