//
//  ProductDetailsInteractor.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 20/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsBusinessLogic {
    func requestProductDetails()
}

protocol ProductDetailsDataStore {
    var product: ProductModel? { get set }
}

class ProductDetailsInteractor: ProductDetailsBusinessLogic, ProductDetailsDataStore {

    var presenter: ProductDetailsPresentationLogic?
    var worker: ProductDetailsWorker?
    var product: ProductModel?
    
    func requestProductDetails() {
        if let product = self.product {
            presenter?.presentProductDetails(product: product)
        }
    }

}
