//
//  HomePresenter.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 14/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentSomething(response: Home.Something.Response)
    func presentNavigationLogo()
}

class HomePresenter: HomePresentationLogic {

    weak var viewController: HomeDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Home.Something.Response) {
        let viewModel = Home.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentNavigationLogo() {
        viewController?.displayNavigationLogo()
    }
    
}
