//
//  HomePresenter.swift
//  Test.AmeDigitalLodjinha
//
//  Created by Leandro Romano on 14/06/19.
//  Copyright (c) 2019 Leandro Romano. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol HomePresentationLogic {
    func presentNavigationLogo()
    func presentBannersLoading()
    func presentBanners(response: Home.Banner.Response)
    func presentBannersError()
    func presentNewData()
    func presentBestSellerDetails()
    func presentProductsListByCategory()
}

class HomePresenter: HomePresentationLogic {

    weak var viewController: HomeDisplayLogic?
    
    func presentNavigationLogo() {
        viewController?.displayNavigationLogo()
    }
    
    func presentBannersLoading() {
        viewController?.displayBannersLoading()
    }
    
    func presentBanners(response: Home.Banner.Response) {
        let viewModel: [BannerViewModel] = response.data.map { BannerViewModel(banner: $0) }
        viewController?.displayBanners(viewModel: Home.Banner.ViewModel(banners: viewModel))
    }
    
    func presentBannersError() {
        viewController?.displayBannersError()
    }
    
    func presentNewData() {
        viewController?.displayNewData()
    }
    
    func presentBestSellerDetails() {
        viewController?.displayBestSellerDetails()
    }
    
    func presentProductsListByCategory() {
        viewController?.displayProductsListByCategory()
    }
    
}
